// client/src/store/settings.ts

/* 
 * Settings Store - Centralized State Management for LibreChat User Preferences
 * 
 * This file defines all the application settings using Recoil atoms for state management.
 * Recoil is Facebook's experimental state management library for React applications.
 * 
 * Two types of atoms are created:
 * 1. Static atoms - Store temporary UI state that doesn't persist between sessions
 * 2. LocalStorage atoms - Store user preferences that persist in browser localStorage
 */

import { atom } from 'recoil';
import { SettingsViews, LocalStorageKeys } from 'librechat-data-provider';
import { atomWithLocalStorage } from '~/store/utils';
import type { TOptionSettings } from '~/common';

/* 
 * Static Atoms - Temporary UI State
 * These atoms store transient application state that resets when the user refreshes
 * or closes the browser. They're used for modal dialogs, temporary UI states, etc.
 */
const staticAtoms = {
  // Controls whether automatic scrolling should be interrupted/aborted
  abortScroll: atom<boolean>({ key: 'abortScroll', default: false }),

  // Toggles visibility of the file attachment panel in chat interface
  showFiles: atom<boolean>({ key: 'showFiles', default: false }),

  // Stores dynamic option settings for different AI models/providers
  // TOptionSettings is a TypeScript type defining the structure of model-specific options
  optionSettings: atom<TOptionSettings>({ key: 'optionSettings', default: {} }),

  // Controls visibility of the plugin marketplace modal dialog
  showPluginStoreDialog: atom<boolean>({ key: 'showPluginStoreDialog', default: false }),

  // Toggles the agent configuration panel (for AI assistant settings)
  showAgentSettings: atom<boolean>({ key: 'showAgentSettings', default: false }),

  // Tracks which settings panel is currently active (General, Data, etc.)
  // SettingsViews is an enum from librechat-data-provider defining available views
  currentSettingsView: atom<SettingsViews>({
    key: 'currentSettingsView',
    default: SettingsViews.default,
  }),

  // Controls visibility of tooltip/popover components throughout the app
  showPopover: atom<boolean>({ key: 'showPopover', default: false }),
};

/*
 * LocalStorage Atoms - Persistent User Preferences
 * These atoms automatically sync with browser localStorage, preserving user settings
 * across browser sessions. The atomWithLocalStorage utility handles the persistence logic.
 */
const localStorageAtoms = {
  // === GENERAL UI SETTINGS ===

  // Whether chat messages should automatically scroll to bottom as new messages arrive
  autoScroll: atomWithLocalStorage('autoScroll', false),

  // Collapses the left sidebar (conversation history) to maximize chat space
  hideSidePanel: atomWithLocalStorage('hideSidePanel', false),

  // CSS class for text size throughout the application (text-sm, text-base, text-lg, etc.)
  fontSize: atomWithLocalStorage('fontSize', 'text-base'),

  // Enables Markdown rendering in user messages (bold, italics, lists, etc.)
  // Uses LocalStorageKeys enum for consistent key naming across the codebase
  enableUserMsgMarkdown: atomWithLocalStorage<boolean>(
    LocalStorageKeys.ENABLE_USER_MSG_MARKDOWN,
    true,
  ),

  // === CHAT INTERFACE SETTINGS ===

  // Whether Enter key sends message (true) or Shift+Enter is required (false)
  enterToSend: atomWithLocalStorage('enterToSend', true),

  // Expands chat area by hiding non-essential UI elements
  maximizeChatSpace: atomWithLocalStorage('maximizeChatSpace', false),

  // Text direction for chat messages: 'LTR' (Left-to-Right) or 'RTL' (Right-to-Left)
  // Important for internationalization and right-to-left languages like Arabic/Hebrew
  chatDirection: atomWithLocalStorage('chatDirection', 'LTR'),

  // Shows/hides code analysis blocks generated by AI models
  showCode: atomWithLocalStorage(LocalStorageKeys.SHOW_ANALYSIS_CODE, true),

  // Automatically saves message drafts as user types (prevents loss on accidental refresh)
  saveDrafts: atomWithLocalStorage('saveDrafts', true),

  // Displays scroll-to-bottom button when user scrolls up in long conversations
  showScrollButton: atomWithLocalStorage('showScrollButton', true),

  // Configuration for conversation forking feature (creating branches from messages)
  // Empty string means no default fork setting
  forkSetting: atomWithLocalStorage('forkSetting', ''),

  // Whether to split conversation at a specific target message when forking
  splitAtTarget: atomWithLocalStorage('splitAtTarget', false),

  // Remembers user's preferred fork options between sessions
  rememberDefaultFork: atomWithLocalStorage(LocalStorageKeys.REMEMBER_FORK_OPTION, false),

  // Shows AI "thinking" process before generating final response
  showThinking: atomWithLocalStorage('showThinking', false),

  // Preserves state of achievement/status badges in the UI
  saveBadgesState: atomWithLocalStorage('saveBadgesState', false),

  // === BETA FEATURES ===
  // Experimental features that may become standard or be removed

  // Enables modular chat interface with draggable/resizable components
  modularChat: atomWithLocalStorage('modularChat', true),

  // Renders mathematical expressions using LaTeX notation (e.g., equations, formulas)
  LaTeXParsing: atomWithLocalStorage('LaTeXParsing', true),

  // Centers the main form on the landing page for better visual balance
  centerFormOnLanding: atomWithLocalStorage('centerFormOnLanding', true),

  // Shows/hides footer with links, version info, etc.
  showFooter: atomWithLocalStorage('showFooter', true),

  // === COMMAND SHORTCUTS ===
  // Quick commands for power users to efficiently interact with the chat

  // "@" command for mentioning/tagging specific AI models or users
  atCommand: atomWithLocalStorage('atCommand', true),

  // "+" command for adding attachments, plugins, or expanding functionality
  plusCommand: atomWithLocalStorage('plusCommand', true),

  // "/" command for slash commands (like Discord/Slack style commands)
  slashCommand: atomWithLocalStorage('slashCommand', true),

  // === SPEECH/VOICE SETTINGS ===

  // Enables continuous conversation mode (voice-to-voice chat)
  conversationMode: atomWithLocalStorage('conversationMode', false),

  // Unlocks advanced speech settings and features
  advancedMode: atomWithLocalStorage('advancedMode', false),

  // --- Speech-to-Text (STT) Configuration ---

  // Master toggle for speech-to-text functionality
  speechToText: atomWithLocalStorage('speechToText', true),

  // STT engine: 'browser' (Web Speech API) or cloud services like 'openai'
  engineSTT: atomWithLocalStorage('engineSTT', 'browser'),

  // Language code for speech recognition (e.g., 'en-US', 'es-ES', 'fr-FR')
  // Empty string uses browser default
  languageSTT: atomWithLocalStorage('languageSTT', ''),

  // Automatically starts transcribing when audio is detected
  autoTranscribeAudio: atomWithLocalStorage('autoTranscribeAudio', false),

  // Microphone sensitivity threshold in decibels (negative values)
  // -45 is moderately sensitive, -30 is very sensitive, -60 is less sensitive
  decibelValue: atomWithLocalStorage('decibelValue', -45),

  // Auto-send threshold: -1 disabled, positive values set delay in seconds
  autoSendText: atomWithLocalStorage('autoSendText', -1),

  // --- Text-to-Speech (TTS) Configuration ---

  // Master toggle for text-to-speech functionality
  textToSpeech: atomWithLocalStorage('textToSpeech', true),

  // TTS engine: 'browser' (Web Speech API) or cloud services
  engineTTS: atomWithLocalStorage('engineTTS', 'browser'),

  // Specific voice selection (varies by browser and installed voices)
  // string | undefined allows for no voice selection (uses default)
  voice: atomWithLocalStorage<string | undefined>('voice', undefined),

  // Use cloud-based voices instead of local browser voices for better quality
  cloudBrowserVoices: atomWithLocalStorage('cloudBrowserVoices', false),

  // Language for text-to-speech output
  languageTTS: atomWithLocalStorage('languageTTS', ''),

  // Automatically starts playing audio when AI response is ready
  automaticPlayback: atomWithLocalStorage('automaticPlayback', false),

  // Speech playback speed multiplier (1.0 = normal, 0.5 = half speed, 2.0 = double speed)
  // null uses system default
  playbackRate: atomWithLocalStorage<number | null>('playbackRate', null),

  // Caches generated audio to reduce API calls and improve performance
  cacheTTS: atomWithLocalStorage('cacheTTS', true),

  // === ACCOUNT/PROFILE SETTINGS ===

  // Shows username in chat interface (vs anonymous/generic display)
  UsernameDisplay: atomWithLocalStorage('UsernameDisplay', true),
};

/*
 * Export Combined Settings Store
 * 
 * This default export merges both static and localStorage atoms into a single object.
 * Components throughout the app can import this store and access any setting using:
 * 
 * import settings from '~/store/settings';
 * const [fontSize] = useRecoilState(settings.fontSize);
 * 
 * The spread operator (...) creates a shallow copy and combines both objects.
 */
export default { ...staticAtoms, ...localStorageAtoms };